use v6;
use Test;

use ManulC::Parser::HTML;
#no precompilation;
#use Grammar::Tracer;

grammar TestHTML does HTML-Tag {
    rule TOP { <mdHTMLTag> }
}

subtest {
    my %tests =
        "simple tag - structure" =>
        { 
            tag => "<a>",
            struct =>
                Match.new(list => (), hash => Map.new((:mdHTMLTag(Match.new(list => (Match.new(list => (), hash => Map.new((:mdHTMLStartTag(Match.new(list => (), hash => Map.new((:mdHTMLAttribute([]),:mdHTMLTagName(Match.new(list => (), hash => Map.new((:alnum([]),:alpha(Match.new(list => (), hash => Map.new(()), pos => 2, from => 1, orig => "<a>", made => Any)))), pos => 2, from => 1, orig => "<a>", made => Any)))), pos => 2, from => 1, orig => "<a>", made => Any)))), pos => 2, from => 1, orig => "<a>", made => Any),), hash => Map.new(()), pos => 3, from => 0, orig => "<a>", made => Any)))), pos => 3, from => 0, orig => "<a>", made => Any),
        },
        "simple tag with space" =>
        {
            tag => "<a >",
            struct =>
                Match.new(hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new(()), from => 0, list => (Match.new(hash => Map.new((:mdHTMLStartTag(Match.new(hash => Map.new((:mdHTMLAttribute([]),:mdHTMLTagName(Match.new(hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), from => 1, list => (), made => Any, pos => 2, orig => "<a >")))), from => 1, list => (), made => Any, pos => 2, orig => "<a >")))), from => 1, list => (), made => Any, pos => 3, orig => "<a >")))), from => 1, list => (), made => Any, pos => 3, orig => "<a >"),), made => Any, pos => 4, orig => "<a >")))), from => 0, list => (), made => Any, pos => 4, orig => "<a >"),
        },
        "keyword attribute value" =>
        {
            tag => "<a href=keyword>",
            struct =>
                Match.new(list => (), made => Any, hash => Map.new((:mdHTMLTag(Match.new(list => (Match.new(list => (), made => Any, hash => Map.new((:mdHTMLStartTag(Match.new(list => (), made => Any, hash => Map.new((:mdHTMLAttribute([Match.new(list => (), made => Any, hash => Map.new((:mdHTMLAttrName(Match.new(list => (), made => Any, hash => Map.new(()), pos => 7, orig => "<a href=keyword>", from => 3)),:mdHTMLAttrVal(Match.new(list => (), made => Any, hash => Map.new((:mdHTMLValue(Match.new(list => (), made => Any, hash => Map.new((:mdHTMLCharText([Match.new(list => (), made => Any, hash => Map.new(()), pos => 15, orig => "<a href=keyword>", from => 8)]),:mdHTMLEntity([]))), pos => 15, orig => "<a href=keyword>", from => 8)))), pos => 15, orig => "<a href=keyword>", from => 8)))), pos => 15, orig => "<a href=keyword>", from => 3)]),:mdHTMLTagName(Match.new(list => (), made => Any, hash => Map.new((:alnum([]),:alpha(Match.new(list => (), made => Any, hash => Map.new(()), pos => 2, orig => "<a href=keyword>", from => 1)))), pos => 2, orig => "<a href=keyword>", from => 1)))), pos => 15, orig => "<a href=keyword>", from => 1)))), pos => 15, orig => "<a href=keyword>", from => 1),), made => Any, hash => Map.new(()), pos => 16, orig => "<a href=keyword>", from => 0)))), pos => 16, orig => "<a href=keyword>", from => 0),
        },
        "double-quoted attribute value" =>
        {
            tag => q{<a href="keyword">},
            struct =>
                Match.new(hash => Map.new((:mdHTMLTag(Match.new(made => Any, pos => 18, list => (Match.new(orig => "<a href=\"keyword\">", made => Any, pos => 17, from => 1, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a href=\"keyword\">", hash => Map.new((:mdHTMLAttribute([Match.new(pos => 17, made => Any, from => 3, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(hash => Map.new(()), from => 3, list => (), made => Any, pos => 7, orig => "<a href=\"keyword\">")),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(hash => Map.new(()), list => (), from => 8, pos => 9, made => Any, orig => "<a href=\"keyword\">")),:mdHTMLValue(Match.new(orig => "<a href=\"keyword\">", hash => Map.new((:mdHTMLCharText([Match.new(list => (), from => 9, pos => 16, made => Any, hash => Map.new(()), orig => "<a href=\"keyword\">")]),:mdHTMLEntity([]))), pos => 16, made => Any, from => 9, list => ())))), list => (), from => 8, made => Any, pos => 17, orig => "<a href=\"keyword\">")))), orig => "<a href=\"keyword\">")]),:mdHTMLTagName(Match.new(from => 1, list => (), made => Any, pos => 2, hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), made => Any, pos => 2, from => 1, list => (), orig => "<a href=\"keyword\">")))), orig => "<a href=\"keyword\">")))), from => 1, list => (), pos => 17, made => Any))))),), from => 0, hash => Map.new(()), orig => "<a href=\"keyword\">")))), from => 0, list => (), made => Any, pos => 18, orig => "<a href=\"keyword\">"),
        },
        "single-quoted attribute value" =>
        {
            tag => q{<a href='keyword'>},
            struct =>
                Match.new(list => (), from => 0, made => Any, pos => 18, hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new(()), made => Any, pos => 18, list => (Match.new(hash => Map.new((:mdHTMLStartTag(Match.new(list => (), from => 1, made => Any, pos => 17, hash => Map.new((:mdHTMLAttribute([Match.new(hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href='keyword'>", hash => Map.new(()), list => (), from => 3, pos => 7, made => Any)),:mdHTMLAttrVal(Match.new(list => (), from => 8, made => Any, pos => 17, hash => Map.new((:mdHTMLValQuot(Match.new(hash => Map.new(()), list => (), from => 8, pos => 9, made => Any, orig => "<a href='keyword'>")),:mdHTMLValue(Match.new(orig => "<a href='keyword'>", hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href='keyword'>", hash => Map.new(()), pos => 16, made => Any, from => 9, list => ())]),:mdHTMLEntity([]))), list => (), from => 9, made => Any, pos => 16)))), orig => "<a href='keyword'>")))), pos => 17, made => Any, list => (), from => 3, orig => "<a href='keyword'>")]),:mdHTMLTagName(Match.new(orig => "<a href='keyword'>", hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), from => 1, list => (), made => Any, pos => 2, orig => "<a href='keyword'>")))), pos => 2, made => Any, from => 1, list => ())))), orig => "<a href='keyword'>")))), from => 1, list => (), made => Any, pos => 17, orig => "<a href='keyword'>"),), from => 0, orig => "<a href='keyword'>")))), orig => "<a href='keyword'>"),
        },
        "keyword attribute value / named char inside" =>
        {
            tag => "<a href=key&dot;word>",
            struct =>
                Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLTag(Match.new(list => (Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLStartTag(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLAttribute([Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLAttrName(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 7, made => Any, from => 3)),:mdHTMLAttrVal(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLValue(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLCharText([Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 11, made => Any, from => 8), Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 20, made => Any, from => 16)]),:mdHTMLEntity([Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:mdHTMLCharReference(Match.new(list => (Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 15, made => Any, from => 12),), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 15, made => Any, from => 12)))), pos => 16, made => Any, from => 11)]))), pos => 20, made => Any, from => 8)))), pos => 20, made => Any, from => 8)))), pos => 20, made => Any, from => 3)]),:mdHTMLTagName(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new((:alnum([]),:alpha(Match.new(list => (), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 2, made => Any, from => 1)))), pos => 2, made => Any, from => 1)))), pos => 20, made => Any, from => 1)))), pos => 20, made => Any, from => 1),), orig => "<a href=key\&dot;word>", hash => Map.new(()), pos => 21, made => Any, from => 0)))), pos => 21, made => Any, from => 0),
        },
        "double-quoted attribute value / named char inside" =>
        {
            tag => q{<a href="key&dot;word">},
            struct =>
                Match.new(orig => "<a href=\"key\&dot;word\">", hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href=\"key\&dot;word\">", hash => Map.new(()), list => (Match.new(orig => "<a href=\"key\&dot;word\">", pos => 22, made => Any, list => (), from => 1, hash => Map.new((:mdHTMLStartTag(Match.new(hash => Map.new((:mdHTMLAttribute([Match.new(hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=\"key\&dot;word\">", hash => Map.new(()), pos => 7, made => Any, list => (), from => 3)),:mdHTMLAttrVal(Match.new(orig => "<a href=\"key\&dot;word\">", list => (), from => 8, made => Any, pos => 22, hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href=\"key\&dot;word\">", made => Any, pos => 9, from => 8, list => (), hash => Map.new(()))),:mdHTMLValue(Match.new(orig => "<a href=\"key\&dot;word\">", made => Any, pos => 21, from => 9, list => (), hash => Map.new((:mdHTMLCharText([Match.new(made => Any, pos => 12, list => (), from => 9, hash => Map.new(()), orig => "<a href=\"key\&dot;word\">"), Match.new(pos => 21, made => Any, from => 17, list => (), hash => Map.new(()), orig => "<a href=\"key\&dot;word\">")]),:mdHTMLEntity([Match.new(pos => 17, made => Any, list => (), from => 12, hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=\"key\&dot;word\">", hash => Map.new(()), list => (Match.new(hash => Map.new(()), list => (), from => 13, made => Any, pos => 16, orig => "<a href=\"key\&dot;word\">"),), from => 13, pos => 16, made => Any)))), orig => "<a href=\"key\&dot;word\">")]))))))))))), list => (), from => 3, made => Any, pos => 22, orig => "<a href=\"key\&dot;word\">")]),:mdHTMLTagName(Match.new(list => (), from => 1, pos => 2, made => Any, hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), list => (), from => 1, pos => 2, made => Any, orig => "<a href=\"key\&dot;word\">")))), orig => "<a href=\"key\&dot;word\">")))), from => 1, list => (), pos => 22, made => Any, orig => "<a href=\"key\&dot;word\">"))))),), from => 0, pos => 23, made => Any)))), list => (), from => 0, pos => 23, made => Any),
        },
        "single-quoted attribute value / named char inside" =>
        {
            tag => q{<a href='key&dot;word'>},
            struct =>
                Match.new(from => 0, list => (), made => Any, pos => 23, hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href='key\&dot;word'>", hash => Map.new(()), made => Any, pos => 23, from => 0, list => (Match.new(hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a href='key\&dot;word'>", from => 1, list => (), pos => 22, made => Any, hash => Map.new((:mdHTMLAttribute([Match.new(orig => "<a href='key\&dot;word'>", pos => 22, made => Any, list => (), from => 3, hash => Map.new((:mdHTMLAttrName(Match.new(pos => 7, made => Any, from => 3, list => (), hash => Map.new(()), orig => "<a href='key\&dot;word'>")),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href='key\&dot;word'>", hash => Map.new(()), list => (), from => 8, pos => 9, made => Any)),:mdHTMLValue(Match.new(orig => "<a href='key\&dot;word'>", hash => Map.new((:mdHTMLCharText([Match.new(hash => Map.new(()), pos => 12, made => Any, from => 9, list => (), orig => "<a href='key\&dot;word'>"), Match.new(pos => 21, made => Any, from => 17, list => (), hash => Map.new(()), orig => "<a href='key\&dot;word'>")]),:mdHTMLEntity([Match.new(orig => "<a href='key\&dot;word'>", hash => Map.new((:mdHTMLCharReference(Match.new(from => 13, list => (Match.new(pos => 16, made => Any, list => (), from => 13, hash => Map.new(()), orig => "<a href='key\&dot;word'>"),), made => Any, pos => 16, hash => Map.new(()), orig => "<a href='key\&dot;word'>")))), pos => 17, made => Any, list => (), from => 12)]))), list => (), from => 9, pos => 21, made => Any)))), from => 8, list => (), made => Any, pos => 22, orig => "<a href='key\&dot;word'>")))))]),:mdHTMLTagName(Match.new(orig => "<a href='key\&dot;word'>", from => 1, list => (), pos => 2, made => Any, hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), made => Any, pos => 2, from => 1, list => (), orig => "<a href='key\&dot;word'>")))))))))))), pos => 22, made => Any, from => 1, list => (), orig => "<a href='key\&dot;word'>"),))))), orig => "<a href='key\&dot;word'>"),
        },
        "keyword attribute value / named char at end" =>
        {
            tag => "<a href=keyword&quot;>",
            struct =>
                Match.new(made => Any, hash => Map.new((:mdHTMLTag(Match.new(made => Any, hash => Map.new(()), pos => 22, list => (Match.new(made => Any, hash => Map.new((:mdHTMLStartTag(Match.new(made => Any, hash => Map.new((:mdHTMLAttribute([Match.new(made => Any, hash => Map.new((:mdHTMLAttrName(Match.new(made => Any, hash => Map.new(()), pos => 7, list => (), from => 3, orig => "<a href=keyword\&quot;>")),:mdHTMLAttrVal(Match.new(made => Any, hash => Map.new((:mdHTMLValue(Match.new(made => Any, hash => Map.new((:mdHTMLCharText([Match.new(made => Any, hash => Map.new(()), pos => 15, list => (), from => 8, orig => "<a href=keyword\&quot;>"), Match.new(made => Any, hash => Map.new(()), pos => 21, list => (), from => 21, orig => "<a href=keyword\&quot;>")]),:mdHTMLEntity([Match.new(made => Any, hash => Map.new((:mdHTMLCharReference(Match.new(made => Any, hash => Map.new(()), pos => 20, list => (Match.new(made => Any, hash => Map.new(()), pos => 20, list => (), from => 16, orig => "<a href=keyword\&quot;>"),), from => 16, orig => "<a href=keyword\&quot;>")))), pos => 21, list => (), from => 15, orig => "<a href=keyword\&quot;>")]))), pos => 21, list => (), from => 8, orig => "<a href=keyword\&quot;>")))), pos => 21, list => (), from => 8, orig => "<a href=keyword\&quot;>")))), pos => 21, list => (), from => 3, orig => "<a href=keyword\&quot;>")]),:mdHTMLTagName(Match.new(made => Any, hash => Map.new((:alnum([]),:alpha(Match.new(made => Any, hash => Map.new(()), pos => 2, list => (), from => 1, orig => "<a href=keyword\&quot;>")))), pos => 2, list => (), from => 1, orig => "<a href=keyword\&quot;>")))), pos => 21, list => (), from => 1, orig => "<a href=keyword\&quot;>")))), pos => 21, list => (), from => 1, orig => "<a href=keyword\&quot;>"),), from => 0, orig => "<a href=keyword\&quot;>")))), pos => 22, list => (), from => 0, orig => "<a href=keyword\&quot;>"),
        },
        "double-quoted attribute value / named char at end" =>
        {
            tag => q{<a href="keyword&quot;">},
            struct =>
                Match.new(orig => "<a href=\"keyword\&quot;\">", list => (), from => 0, made => Any, pos => 24, hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new(()), made => Any, pos => 24, list => (Match.new(orig => "<a href=\"keyword\&quot;\">", hash => Map.new((:mdHTMLStartTag(Match.new(pos => 23, made => Any, from => 1, list => (), hash => Map.new((:mdHTMLAttribute([Match.new(hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=\"keyword\&quot;\">", pos => 7, made => Any, from => 3, list => (), hash => Map.new(()))),:mdHTMLAttrVal(Match.new(orig => "<a href=\"keyword\&quot;\">", hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href=\"keyword\&quot;\">", from => 8, list => (), pos => 9, made => Any, hash => Map.new(()))),:mdHTMLValue(Match.new(orig => "<a href=\"keyword\&quot;\">", hash => Map.new((:mdHTMLCharText([Match.new(hash => Map.new(()), from => 9, list => (), made => Any, pos => 16, orig => "<a href=\"keyword\&quot;\">"), Match.new(hash => Map.new(()), made => Any, pos => 22, from => 22, list => (), orig => "<a href=\"keyword\&quot;\">")]),:mdHTMLEntity([Match.new(orig => "<a href=\"keyword\&quot;\">", hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=\"keyword\&quot;\">", hash => Map.new(()), made => Any, pos => 21, from => 17, list => (Match.new(hash => Map.new(()), pos => 21, made => Any, from => 17, list => (), orig => "<a href=\"keyword\&quot;\">"),))))), made => Any, pos => 22, list => (), from => 16)]))), made => Any, pos => 22, from => 9, list => ())))), made => Any, pos => 23, from => 8, list => ())))), list => (), from => 3, made => Any, pos => 23, orig => "<a href=\"keyword\&quot;\">")]),:mdHTMLTagName(Match.new(from => 1, list => (), made => Any, pos => 2, hash => Map.new((:alnum([]),:alpha(Match.new(orig => "<a href=\"keyword\&quot;\">", made => Any, pos => 2, list => (), from => 1, hash => Map.new(()))))), orig => "<a href=\"keyword\&quot;\">")))), orig => "<a href=\"keyword\&quot;\">")))), pos => 23, made => Any, from => 1, list => ()),), from => 0, orig => "<a href=\"keyword\&quot;\">"))))),
        },
        "single-quoted attribute value / named char at end" =>
        {
            tag => q{<a href='keyword&quot;'>},
            struct =>
                Match.new(orig => "<a href='keyword\&quot;'>", made => Any, from => 0, list => (), pos => 24, hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new(()), list => (Match.new(made => Any, orig => "<a href='keyword\&quot;'>", from => 1, pos => 23, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(pos => 23, list => (), hash => Map.new((:mdHTMLAttribute([Match.new(pos => 23, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(hash => Map.new(()), pos => 7, list => (), from => 3, orig => "<a href='keyword\&quot;'>", made => Any)),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(pos => 9, list => (), hash => Map.new(()), made => Any, orig => "<a href='keyword\&quot;'>", from => 8)),:mdHTMLValue(Match.new(from => 9, made => Any, orig => "<a href='keyword\&quot;'>", hash => Map.new((:mdHTMLCharText([Match.new(from => 9, orig => "<a href='keyword\&quot;'>", made => Any, hash => Map.new(()), list => (), pos => 16), Match.new(orig => "<a href='keyword\&quot;'>", made => Any, from => 22, list => (), pos => 22, hash => Map.new(()))]),:mdHTMLEntity([Match.new(hash => Map.new((:mdHTMLCharReference(Match.new(from => 17, made => Any, orig => "<a href='keyword\&quot;'>", hash => Map.new(()), list => (Match.new(pos => 21, list => (), hash => Map.new(()), orig => "<a href='keyword\&quot;'>", made => Any, from => 17),), pos => 21)))), pos => 22, list => (), from => 16, orig => "<a href='keyword\&quot;'>", made => Any)]))), list => (), pos => 22)))), list => (), pos => 23, from => 8, made => Any, orig => "<a href='keyword\&quot;'>")))), orig => "<a href='keyword\&quot;'>", made => Any, from => 3)]),:mdHTMLTagName(Match.new(from => 1, orig => "<a href='keyword\&quot;'>", made => Any, hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, list => (), hash => Map.new(()), made => Any, orig => "<a href='keyword\&quot;'>", from => 1)))), pos => 2, list => ())))), orig => "<a href='keyword\&quot;'>", made => Any, from => 1))))),), pos => 24, from => 0, orig => "<a href='keyword\&quot;'>", made => Any))))),
        },
        "keyword attribute value / named char at start" =>
        {
            tag => "<a href=&apos;keyword>",
            struct =>
                Match.new(pos => 22, list => (), hash => Map.new((:mdHTMLTag(Match.new(list => (Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 1, list => (), pos => 21, hash => Map.new((:mdHTMLStartTag(Match.new(made => Any, orig => "<a href=\&apos;keyword>", from => 1, list => (), pos => 21, hash => Map.new((:mdHTMLAttribute([Match.new(from => 3, orig => "<a href=\&apos;keyword>", made => Any, hash => Map.new((:mdHTMLAttrName(Match.new(list => (), pos => 7, hash => Map.new(()), orig => "<a href=\&apos;keyword>", made => Any, from => 3)),:mdHTMLAttrVal(Match.new(from => 8, made => Any, orig => "<a href=\&apos;keyword>", hash => Map.new((:mdHTMLValue(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 8, pos => 21, list => (), hash => Map.new((:mdHTMLCharText([Match.new(from => 8, made => Any, orig => "<a href=\&apos;keyword>", hash => Map.new(()), list => (), pos => 8), Match.new(pos => 21, list => (), hash => Map.new(()), orig => "<a href=\&apos;keyword>", made => Any, from => 14)]),:mdHTMLEntity([Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 8, list => (), pos => 14, hash => Map.new((:mdHTMLCharReference(Match.new(from => 9, orig => "<a href=\&apos;keyword>", made => Any, hash => Map.new(()), pos => 13, list => (Match.new(pos => 13, list => (), hash => Map.new(()), made => Any, orig => "<a href=\&apos;keyword>", from => 9),))))))]))))))), list => (), pos => 21)))), list => (), pos => 21)]),:mdHTMLTagName(Match.new(pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 1, pos => 2, list => (), hash => Map.new(()))))), orig => "<a href=\&apos;keyword>", made => Any, from => 1))))))))),), pos => 22, hash => Map.new(()), made => Any, orig => "<a href=\&apos;keyword>", from => 0)))), orig => "<a href=\&apos;keyword>", made => Any, from => 0),
        },
        "double-quoted attribute value / named char at start" =>
        {
            tag => q{<a href="&apos;keyword">},
            struct =>
                Match.new(hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new(()), made => Any, pos => 24, list => (Match.new(orig => "<a href=\"\&apos;keyword\">", made => Any, pos => 23, list => (), from => 1, hash => Map.new((:mdHTMLStartTag(Match.new(pos => 23, made => Any, list => (), from => 1, hash => Map.new((:mdHTMLAttribute([Match.new(pos => 23, made => Any, list => (), from => 3, hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=\"\&apos;keyword\">", hash => Map.new(()), made => Any, pos => 7, from => 3, list => ())),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(hash => Map.new(()), pos => 9, made => Any, list => (), from => 8, orig => "<a href=\"\&apos;keyword\">")),:mdHTMLValue(Match.new(made => Any, pos => 22, list => (), from => 9, hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href=\"\&apos;keyword\">", hash => Map.new(()), made => Any, pos => 9, list => (), from => 9), Match.new(orig => "<a href=\"\&apos;keyword\">", made => Any, pos => 22, list => (), from => 15, hash => Map.new(()))]),:mdHTMLEntity([Match.new(orig => "<a href=\"\&apos;keyword\">", from => 9, list => (), made => Any, pos => 15, hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=\"\&apos;keyword\">", pos => 14, made => Any, from => 10, list => (Match.new(hash => Map.new(()), from => 10, list => (), pos => 14, made => Any, orig => "<a href=\"\&apos;keyword\">"),), hash => Map.new(()))))))]))), orig => "<a href=\"\&apos;keyword\">")))), from => 8, list => (), pos => 23, made => Any, orig => "<a href=\"\&apos;keyword\">")))), orig => "<a href=\"\&apos;keyword\">")]),:mdHTMLTagName(Match.new(hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), list => (), from => 1, made => Any, pos => 2, orig => "<a href=\"\&apos;keyword\">")))), pos => 2, made => Any, from => 1, list => (), orig => "<a href=\"\&apos;keyword\">")))), orig => "<a href=\"\&apos;keyword\">"))))),), from => 0, orig => "<a href=\"\&apos;keyword\">")))), list => (), from => 0, pos => 24, made => Any, orig => "<a href=\"\&apos;keyword\">"),
        },
        "single-quoted attribute value / named char at start" =>
        {
            tag => q{<a href='&apos;keyword'>},
            struct =>
                Match.new(orig => "<a href='\&apos;keyword'>", from => 0, made => Any, pos => 24, hash => Map.new((:mdHTMLTag(Match.new(made => Any, from => 0, orig => "<a href='\&apos;keyword'>", list => (Match.new(hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a href='\&apos;keyword'>", from => 1, made => Any, hash => Map.new((:mdHTMLAttribute([Match.new(made => Any, from => 3, orig => "<a href='\&apos;keyword'>", list => (), hash => Map.new((:mdHTMLAttrName(Match.new(pos => 7, hash => Map.new(()), list => (), orig => "<a href='\&apos;keyword'>", from => 3, made => Any)),:mdHTMLAttrVal(Match.new(list => (), pos => 23, hash => Map.new((:mdHTMLValQuot(Match.new(list => (), pos => 9, hash => Map.new(()), made => Any, from => 8, orig => "<a href='\&apos;keyword'>")),:mdHTMLValue(Match.new(list => (), pos => 22, hash => Map.new((:mdHTMLCharText([Match.new(list => (), pos => 9, hash => Map.new(()), made => Any, from => 9, orig => "<a href='\&apos;keyword'>"), Match.new(made => Any, orig => "<a href='\&apos;keyword'>", from => 15, list => (), hash => Map.new(()), pos => 22)]),:mdHTMLEntity([Match.new(list => (), pos => 15, hash => Map.new((:mdHTMLCharReference(Match.new(from => 10, orig => "<a href='\&apos;keyword'>", made => Any, hash => Map.new(()), pos => 14, list => (Match.new(made => Any, from => 10, orig => "<a href='\&apos;keyword'>", list => (), hash => Map.new(()), pos => 14),))))), made => Any, orig => "<a href='\&apos;keyword'>", from => 9)]))), made => Any, orig => "<a href='\&apos;keyword'>", from => 9)))), made => Any, orig => "<a href='\&apos;keyword'>", from => 8)))), pos => 23)]),:mdHTMLTagName(Match.new(made => Any, from => 1, orig => "<a href='\&apos;keyword'>", list => (), pos => 2, hash => Map.new((:alnum([]),:alpha(Match.new(made => Any, orig => "<a href='\&apos;keyword'>", from => 1, list => (), pos => 2, hash => Map.new(()))))))))), pos => 23, list => ())))), pos => 23, list => (), from => 1, orig => "<a href='\&apos;keyword'>", made => Any),), pos => 24, hash => Map.new(()))))), list => ()),
        },
        ;

    plan %tests.keys.elems;

    for %tests.keys -> $test {
        my $match = TestHTML.parse( %tests{$test}<tag> );
        #diag $match.gist;
        is-deeply
            $match,
            %tests{$test}<struct>,
            $test;
    }
}, "Matches";

subtest {
    my $match;

    $match = TestHTML.parse("< a>");
    nok($match.defined, "space before tag name");
}, "Non-matches";

done-testing;

# vim: ft=perl6
