use v6;
use Test;

use ManulC::Parser::HTML;
#no precompilation;
#use Grammar::Tracer;

grammar TestHTML does HTML-Tag {
    rule TOP { <mdHTMLTag> }
}

subtest {
    my %tests =
        "keyword attribute value / named char inside" => {
            tag       => q{<a href=key&dot;word>},
            struct => Match.new(list => (), hash => Map.new((:mdHTMLTag(Match.new(hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a href=key\&dot;word>", from => 1, made => Any, list => (), hash => Map.new((:mdHTMLAttribute([Match.new(pos => 20, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(list => (), hash => Map.new(()), pos => 7, orig => "<a href=key\&dot;word>", from => 3, made => Any)),:mdHTMLAttrVal(Match.new(pos => 20, list => (), hash => Map.new((:mdHTMLValue(Match.new(from => 8, made => Any, orig => "<a href=key\&dot;word>", pos => 20, hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href=key\&dot;word>", made => Any, from => 8, list => (), hash => Map.new(()), pos => 11), Match.new(pos => 20, hash => Map.new(()), list => (), made => Any, from => 16, orig => "<a href=key\&dot;word>")]),:mdHTMLEntity([Match.new(pos => 16, list => (), hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=key\&dot;word>", from => 12, made => Any, list => (), hash => Map.new(()), pos => 15)))), made => Any, from => 11, orig => "<a href=key\&dot;word>")]))), list => ())))), made => Any, from => 8, orig => "<a href=key\&dot;word>")))), made => Any, from => 3, orig => "<a href=key\&dot;word>")]),:mdHTMLTagName(Match.new(orig => "<a href=key\&dot;word>", from => 1, made => Any, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, list => (), hash => Map.new(()), from => 1, made => Any, orig => "<a href=key\&dot;word>")))), pos => 2)))), pos => 20)))), list => (), pos => 21, orig => "<a href=key\&dot;word>", made => Any, from => 0)))), pos => 21, orig => "<a href=key\&dot;word>", made => Any, from => 0)
        },
        "single-quoted attribute value / named char at end" => {
            tag       => q{<a href='keyword&quot;'>},
            struct => Match.new(made => Any, from => 0, orig => "<a href='keyword\&quot;'>", pos => 24, hash => Map.new((:mdHTMLTag(Match.new(pos => 24, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(made => Any, from => 1, orig => "<a href='keyword\&quot;'>", pos => 23, hash => Map.new((:mdHTMLAttribute([Match.new(made => Any, from => 3, orig => "<a href='keyword\&quot;'>", pos => 23, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(list => (), hash => Map.new(()), pos => 7, orig => "<a href='keyword\&quot;'>", made => Any, from => 3)),:mdHTMLAttrVal(Match.new(pos => 23, hash => Map.new((:mdHTMLValQuot(Match.new(pos => 9, hash => Map.new(()), list => (), made => Any, from => 8, orig => "<a href='keyword\&quot;'>")),:mdHTMLValue(Match.new(list => (), hash => Map.new((:mdHTMLCharText([Match.new(pos => 16, list => (), hash => Map.new(()), from => 9, made => Any, orig => "<a href='keyword\&quot;'>"), Match.new(from => 22, made => Any, orig => "<a href='keyword\&quot;'>", pos => 22, list => (), hash => Map.new(()))]),:mdHTMLEntity([Match.new(pos => 22, hash => Map.new((:mdHTMLCharReference(Match.new(hash => Map.new(()), list => (), pos => 21, orig => "<a href='keyword\&quot;'>", made => Any, from => 17)))), list => (), made => Any, from => 16, orig => "<a href='keyword\&quot;'>")]))), pos => 22, orig => "<a href='keyword\&quot;'>", from => 9, made => Any)))), list => (), made => Any, from => 8, orig => "<a href='keyword\&quot;'>")))))]),:mdHTMLTagName(Match.new(list => (), hash => Map.new((:alnum([]),:alpha(Match.new(made => Any, from => 1, orig => "<a href='keyword\&quot;'>", pos => 2, list => (), hash => Map.new(()))))), pos => 2, orig => "<a href='keyword\&quot;'>", from => 1, made => Any)))), list => ())))), made => Any, from => 0, orig => "<a href='keyword\&quot;'>")))), list => ())
        },
        "double-quoted attribute value / named char at end" => {
            tag       => q{<a href="keyword&quot;">},
            struct => Match.new(from => 0, made => Any, orig => "<a href=\"keyword\&quot;\">", pos => 24, list => (), hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href=\"keyword\&quot;\">", from => 0, made => Any, hash => Map.new((:mdHTMLStartTag(Match.new(list => (), hash => Map.new((:mdHTMLAttribute([Match.new(list => (), hash => Map.new((:mdHTMLAttrName(Match.new(list => (), hash => Map.new(()), pos => 7, orig => "<a href=\"keyword\&quot;\">", made => Any, from => 3)),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(from => 8, made => Any, orig => "<a href=\"keyword\&quot;\">", pos => 9, list => (), hash => Map.new(()))),:mdHTMLValue(Match.new(hash => Map.new((:mdHTMLCharText([Match.new(list => (), hash => Map.new(()), pos => 16, orig => "<a href=\"keyword\&quot;\">", from => 9, made => Any), Match.new(pos => 22, list => (), hash => Map.new(()), made => Any, from => 22, orig => "<a href=\"keyword\&quot;\">")]),:mdHTMLEntity([Match.new(pos => 22, hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=\"keyword\&quot;\">", from => 17, made => Any, hash => Map.new(()), list => (), pos => 21)))), list => (), from => 16, made => Any, orig => "<a href=\"keyword\&quot;\">")]))), list => (), pos => 22, orig => "<a href=\"keyword\&quot;\">", made => Any, from => 9)))), list => (), pos => 23, orig => "<a href=\"keyword\&quot;\">", from => 8, made => Any)))), pos => 23, orig => "<a href=\"keyword\&quot;\">", made => Any, from => 3)]),:mdHTMLTagName(Match.new(pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, list => (), hash => Map.new(()), made => Any, from => 1, orig => "<a href=\"keyword\&quot;\">")))), made => Any, from => 1, orig => "<a href=\"keyword\&quot;\">")))), pos => 23, orig => "<a href=\"keyword\&quot;\">", from => 1, made => Any)))), list => (), pos => 24)))))
        },
        "simple tag with space" => {
            tag       => q{<a >},
            struct => Match.new(pos => 4, hash => Map.new((:mdHTMLTag(Match.new(orig => "<a >", made => Any, from => 0, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a >", from => 1, made => Any, hash => Map.new((:mdHTMLAttribute([]),:mdHTMLTagName(Match.new(hash => Map.new((:alnum([]),:alpha(Match.new(made => Any, from => 1, orig => "<a >", pos => 2, list => (), hash => Map.new(()))))), list => (), pos => 2, orig => "<a >", made => Any, from => 1)))), list => (), pos => 3)))), pos => 4)))), list => (), made => Any, from => 0, orig => "<a >")
        },
        "single-quoted attribute value / named char at start" => {
            tag       => q{<a href='&apos;keyword'>},
            struct => Match.new(orig => "<a href='\&apos;keyword'>", from => 0, made => Any, hash => Map.new((:mdHTMLTag(Match.new(pos => 24, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(list => (), hash => Map.new((:mdHTMLAttribute([Match.new(orig => "<a href='\&apos;keyword'>", made => Any, from => 3, hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href='\&apos;keyword'>", made => Any, from => 3, hash => Map.new(()), list => (), pos => 7)),:mdHTMLAttrVal(Match.new(made => Any, from => 8, orig => "<a href='\&apos;keyword'>", pos => 23, hash => Map.new((:mdHTMLValQuot(Match.new(pos => 9, list => (), hash => Map.new(()), made => Any, from => 8, orig => "<a href='\&apos;keyword'>")),:mdHTMLValue(Match.new(orig => "<a href='\&apos;keyword'>", from => 9, made => Any, list => (), hash => Map.new((:mdHTMLCharText([Match.new(pos => 9, hash => Map.new(()), list => (), made => Any, from => 9, orig => "<a href='\&apos;keyword'>"), Match.new(list => (), hash => Map.new(()), pos => 22, orig => "<a href='\&apos;keyword'>", made => Any, from => 15)]),:mdHTMLEntity([Match.new(pos => 15, list => (), hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href='\&apos;keyword'>", made => Any, from => 10, hash => Map.new(()), list => (), pos => 14)))), made => Any, from => 9, orig => "<a href='\&apos;keyword'>")]))), pos => 22)))), list => ())))), list => (), pos => 23)]),:mdHTMLTagName(Match.new(from => 1, made => Any, orig => "<a href='\&apos;keyword'>", pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(hash => Map.new(()), list => (), pos => 2, orig => "<a href='\&apos;keyword'>", from => 1, made => Any)))))))), pos => 23, orig => "<a href='\&apos;keyword'>", made => Any, from => 1)))), from => 0, made => Any, orig => "<a href='\&apos;keyword'>")))), list => (), pos => 24)
        },
        "single-quoted attribute value / named char inside" => {
            tag       => q{<a href='key&dot;word'>},
            struct => Match.new(list => (), hash => Map.new((:mdHTMLTag(Match.new(pos => 23, hash => Map.new((:mdHTMLStartTag(Match.new(made => Any, from => 1, orig => "<a href='key\&dot;word'>", pos => 22, hash => Map.new((:mdHTMLAttribute([Match.new(made => Any, from => 3, orig => "<a href='key\&dot;word'>", pos => 22, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href='key\&dot;word'>", from => 3, made => Any, hash => Map.new(()), list => (), pos => 7)),:mdHTMLAttrVal(Match.new(made => Any, from => 8, orig => "<a href='key\&dot;word'>", pos => 22, hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href='key\&dot;word'>", made => Any, from => 8, hash => Map.new(()), list => (), pos => 9)),:mdHTMLValue(Match.new(orig => "<a href='key\&dot;word'>", from => 9, made => Any, hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href='key\&dot;word'>", made => Any, from => 9, hash => Map.new(()), list => (), pos => 12), Match.new(pos => 21, list => (), hash => Map.new(()), made => Any, from => 17, orig => "<a href='key\&dot;word'>")]),:mdHTMLEntity([Match.new(made => Any, from => 12, orig => "<a href='key\&dot;word'>", pos => 17, hash => Map.new((:mdHTMLCharReference(Match.new(list => (), hash => Map.new(()), pos => 16, orig => "<a href='key\&dot;word'>", from => 13, made => Any)))), list => ())]))), list => (), pos => 21)))), list => ())))))]),:mdHTMLTagName(Match.new(hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, hash => Map.new(()), list => (), from => 1, made => Any, orig => "<a href='key\&dot;word'>")))), list => (), pos => 2, orig => "<a href='key\&dot;word'>", from => 1, made => Any)))), list => ())))), list => (), from => 0, made => Any, orig => "<a href='key\&dot;word'>")))), pos => 23, orig => "<a href='key\&dot;word'>", made => Any, from => 0)
        },
        "simple tag - structure" => {
            tag       => q{<a>},
            struct => Match.new(pos => 3, list => (), hash => Map.new((:mdHTMLTag(Match.new(pos => 3, hash => Map.new((:mdHTMLStartTag(Match.new(hash => Map.new((:mdHTMLAttribute([]),:mdHTMLTagName(Match.new(pos => 2, hash => Map.new((:alnum([]),:alpha(Match.new(orig => "<a>", made => Any, from => 1, hash => Map.new(()), list => (), pos => 2)))), list => (), from => 1, made => Any, orig => "<a>")))), list => (), pos => 2, orig => "<a>", made => Any, from => 1)))), list => (), made => Any, from => 0, orig => "<a>")))), made => Any, from => 0, orig => "<a>")
        },
        "double-quoted attribute value / named char at start" => {
            tag       => q{<a href="&apos;keyword">},
            struct => Match.new(orig => "<a href=\"\&apos;keyword\">", made => Any, from => 0, hash => Map.new((:mdHTMLTag(Match.new(list => (), hash => Map.new((:mdHTMLStartTag(Match.new(hash => Map.new((:mdHTMLAttribute([Match.new(hash => Map.new((:mdHTMLAttrName(Match.new(pos => 7, hash => Map.new(()), list => (), made => Any, from => 3, orig => "<a href=\"\&apos;keyword\">")),:mdHTMLAttrVal(Match.new(made => Any, from => 8, orig => "<a href=\"\&apos;keyword\">", pos => 23, list => (), hash => Map.new((:mdHTMLValQuot(Match.new(made => Any, from => 8, orig => "<a href=\"\&apos;keyword\">", pos => 9, list => (), hash => Map.new(()))),:mdHTMLValue(Match.new(pos => 22, hash => Map.new((:mdHTMLCharText([Match.new(hash => Map.new(()), list => (), pos => 9, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 9), Match.new(hash => Map.new(()), list => (), pos => 22, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 15)]),:mdHTMLEntity([Match.new(hash => Map.new((:mdHTMLCharReference(Match.new(list => (), hash => Map.new(()), pos => 14, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 10)))), list => (), pos => 15, orig => "<a href=\"\&apos;keyword\">", from => 9, made => Any)]))), list => (), from => 9, made => Any, orig => "<a href=\"\&apos;keyword\">")))))))), list => (), pos => 23, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 3)]),:mdHTMLTagName(Match.new(pos => 2, hash => Map.new((:alnum([]),:alpha(Match.new(list => (), hash => Map.new(()), pos => 2, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 1)))), list => (), made => Any, from => 1, orig => "<a href=\"\&apos;keyword\">")))), list => (), pos => 23, orig => "<a href=\"\&apos;keyword\">", made => Any, from => 1)))), pos => 24, orig => "<a href=\"\&apos;keyword\">", from => 0, made => Any)))), list => (), pos => 24)
        },
        "double-quoted attribute value / named char inside" => {
            tag       => q{<a href="key&dot;word">},
            struct => Match.new(pos => 23, list => (), hash => Map.new((:mdHTMLTag(Match.new(pos => 23, hash => Map.new((:mdHTMLStartTag(Match.new(hash => Map.new((:mdHTMLAttribute([Match.new(made => Any, from => 3, orig => "<a href=\"key\&dot;word\">", pos => 22, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(pos => 7, hash => Map.new(()), list => (), made => Any, from => 3, orig => "<a href=\"key\&dot;word\">")),:mdHTMLAttrVal(Match.new(hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href=\"key\&dot;word\">", from => 8, made => Any, list => (), hash => Map.new(()), pos => 9)),:mdHTMLValue(Match.new(orig => "<a href=\"key\&dot;word\">", made => Any, from => 9, list => (), hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href=\"key\&dot;word\">", made => Any, from => 9, list => (), hash => Map.new(()), pos => 12), Match.new(pos => 21, hash => Map.new(()), list => (), from => 17, made => Any, orig => "<a href=\"key\&dot;word\">")]),:mdHTMLEntity([Match.new(orig => "<a href=\"key\&dot;word\">", from => 12, made => Any, list => (), hash => Map.new((:mdHTMLCharReference(Match.new(pos => 16, hash => Map.new(()), list => (), made => Any, from => 13, orig => "<a href=\"key\&dot;word\">")))), pos => 17)]))), pos => 21)))), list => (), pos => 22, orig => "<a href=\"key\&dot;word\">", from => 8, made => Any)))))]),:mdHTMLTagName(Match.new(pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(from => 1, made => Any, orig => "<a href=\"key\&dot;word\">", pos => 2, list => (), hash => Map.new(()))))), from => 1, made => Any, orig => "<a href=\"key\&dot;word\">")))), list => (), pos => 22, orig => "<a href=\"key\&dot;word\">", from => 1, made => Any)))), list => (), from => 0, made => Any, orig => "<a href=\"key\&dot;word\">")))), from => 0, made => Any, orig => "<a href=\"key\&dot;word\">")
        },
        "keyword attribute value / named char at start" => {
            tag       => q{<a href=&apos;keyword>},
            struct => Match.new(from => 0, made => Any, orig => "<a href=\&apos;keyword>", pos => 22, list => (), hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 0, hash => Map.new((:mdHTMLStartTag(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 1, hash => Map.new((:mdHTMLAttribute([Match.new(list => (), hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=\&apos;keyword>", from => 3, made => Any, list => (), hash => Map.new(()), pos => 7)),:mdHTMLAttrVal(Match.new(list => (), hash => Map.new((:mdHTMLValue(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 8, hash => Map.new((:mdHTMLCharText([Match.new(hash => Map.new(()), list => (), pos => 8, orig => "<a href=\&apos;keyword>", made => Any, from => 8), Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 14, hash => Map.new(()), list => (), pos => 21)]),:mdHTMLEntity([Match.new(list => (), hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=\&apos;keyword>", made => Any, from => 9, hash => Map.new(()), list => (), pos => 13)))), pos => 14, orig => "<a href=\&apos;keyword>", from => 8, made => Any)]))), list => (), pos => 21)))), pos => 21, orig => "<a href=\&apos;keyword>", from => 8, made => Any)))), pos => 21, orig => "<a href=\&apos;keyword>", made => Any, from => 3)]),:mdHTMLTagName(Match.new(made => Any, from => 1, orig => "<a href=\&apos;keyword>", pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, hash => Map.new(()), list => (), made => Any, from => 1, orig => "<a href=\&apos;keyword>")))))))), list => (), pos => 21)))), list => (), pos => 22)))))
        },
        "keyword attribute value / named char at end" => {
            tag       => q{<a href=keyword&quot;>},
            struct => Match.new(hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href=keyword\&quot;>", from => 0, made => Any, hash => Map.new((:mdHTMLStartTag(Match.new(from => 1, made => Any, orig => "<a href=keyword\&quot;>", pos => 21, hash => Map.new((:mdHTMLAttribute([Match.new(pos => 21, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=keyword\&quot;>", made => Any, from => 3, list => (), hash => Map.new(()), pos => 7)),:mdHTMLAttrVal(Match.new(pos => 21, hash => Map.new((:mdHTMLValue(Match.new(hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href=keyword\&quot;>", made => Any, from => 8, hash => Map.new(()), list => (), pos => 15), Match.new(hash => Map.new(()), list => (), pos => 21, orig => "<a href=keyword\&quot;>", from => 21, made => Any)]),:mdHTMLEntity([Match.new(orig => "<a href=keyword\&quot;>", from => 15, made => Any, list => (), hash => Map.new((:mdHTMLCharReference(Match.new(orig => "<a href=keyword\&quot;>", from => 16, made => Any, list => (), hash => Map.new(()), pos => 20)))), pos => 21)]))), list => (), pos => 21, orig => "<a href=keyword\&quot;>", made => Any, from => 8)))), list => (), from => 8, made => Any, orig => "<a href=keyword\&quot;>")))), from => 3, made => Any, orig => "<a href=keyword\&quot;>")]),:mdHTMLTagName(Match.new(orig => "<a href=keyword\&quot;>", from => 1, made => Any, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(made => Any, from => 1, orig => "<a href=keyword\&quot;>", pos => 2, hash => Map.new(()), list => ())))), pos => 2)))), list => ())))), list => (), pos => 22)))), list => (), pos => 22, orig => "<a href=keyword\&quot;>", made => Any, from => 0)
        },
        "single-quoted attribute value" => {
            tag       => q{<a href='keyword'>},
            struct => Match.new(pos => 18, list => (), hash => Map.new((:mdHTMLTag(Match.new(orig => "<a href='keyword'>", made => Any, from => 0, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(pos => 17, list => (), hash => Map.new((:mdHTMLAttribute([Match.new(orig => "<a href='keyword'>", from => 3, made => Any, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(hash => Map.new(()), list => (), pos => 7, orig => "<a href='keyword'>", made => Any, from => 3)),:mdHTMLAttrVal(Match.new(list => (), hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href='keyword'>", made => Any, from => 8, list => (), hash => Map.new(()), pos => 9)),:mdHTMLValue(Match.new(orig => "<a href='keyword'>", from => 9, made => Any, list => (), hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href='keyword'>", made => Any, from => 9, hash => Map.new(()), list => (), pos => 16)]),:mdHTMLEntity([]))), pos => 16)))), pos => 17, orig => "<a href='keyword'>", from => 8, made => Any)))), pos => 17)]),:mdHTMLTagName(Match.new(made => Any, from => 1, orig => "<a href='keyword'>", pos => 2, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, hash => Map.new(()), list => (), made => Any, from => 1, orig => "<a href='keyword'>")))))))), made => Any, from => 1, orig => "<a href='keyword'>")))), pos => 18)))), made => Any, from => 0, orig => "<a href='keyword'>")
        },
        "double-quoted attribute value" => {
            tag       => q{<a href="keyword">},
            struct => Match.new(orig => "<a href=\"keyword\">", made => Any, from => 0, hash => Map.new((:mdHTMLTag(Match.new(pos => 18, list => (), hash => Map.new((:mdHTMLStartTag(Match.new(list => (), hash => Map.new((:mdHTMLAttribute([Match.new(orig => "<a href=\"keyword\">", made => Any, from => 3, list => (), hash => Map.new((:mdHTMLAttrName(Match.new(orig => "<a href=\"keyword\">", made => Any, from => 3, list => (), hash => Map.new(()), pos => 7)),:mdHTMLAttrVal(Match.new(pos => 17, hash => Map.new((:mdHTMLValQuot(Match.new(orig => "<a href=\"keyword\">", from => 8, made => Any, list => (), hash => Map.new(()), pos => 9)),:mdHTMLValue(Match.new(made => Any, from => 9, orig => "<a href=\"keyword\">", pos => 16, list => (), hash => Map.new((:mdHTMLCharText([Match.new(orig => "<a href=\"keyword\">", from => 9, made => Any, hash => Map.new(()), list => (), pos => 16)]),:mdHTMLEntity([]))))))), list => (), from => 8, made => Any, orig => "<a href=\"keyword\">")))), pos => 17)]),:mdHTMLTagName(Match.new(orig => "<a href=\"keyword\">", made => Any, from => 1, list => (), hash => Map.new((:alnum([]),:alpha(Match.new(orig => "<a href=\"keyword\">", made => Any, from => 1, list => (), hash => Map.new(()), pos => 2)))), pos => 2)))), pos => 17, orig => "<a href=\"keyword\">", from => 1, made => Any)))), made => Any, from => 0, orig => "<a href=\"keyword\">")))), list => (), pos => 18)
        },
        "keyword attribute value" => {
            tag       => q{<a href=keyword>},
            struct => Match.new(pos => 16, hash => Map.new((:mdHTMLTag(Match.new(list => (), hash => Map.new((:mdHTMLStartTag(Match.new(from => 1, made => Any, orig => "<a href=keyword>", pos => 15, hash => Map.new((:mdHTMLAttribute([Match.new(orig => "<a href=keyword>", made => Any, from => 3, hash => Map.new((:mdHTMLAttrName(Match.new(pos => 7, hash => Map.new(()), list => (), made => Any, from => 3, orig => "<a href=keyword>")),:mdHTMLAttrVal(Match.new(pos => 15, hash => Map.new((:mdHTMLValue(Match.new(made => Any, from => 8, orig => "<a href=keyword>", pos => 15, list => (), hash => Map.new((:mdHTMLCharText([Match.new(pos => 15, list => (), hash => Map.new(()), from => 8, made => Any, orig => "<a href=keyword>")]),:mdHTMLEntity([]))))))), list => (), from => 8, made => Any, orig => "<a href=keyword>")))), list => (), pos => 15)]),:mdHTMLTagName(Match.new(list => (), hash => Map.new((:alnum([]),:alpha(Match.new(pos => 2, list => (), hash => Map.new(()), from => 1, made => Any, orig => "<a href=keyword>")))), pos => 2, orig => "<a href=keyword>", made => Any, from => 1)))), list => ())))), pos => 16, orig => "<a href=keyword>", from => 0, made => Any)))), list => (), from => 0, made => Any, orig => "<a href=keyword>")
        },
        ;

    plan %tests.keys.elems;

    for %tests.keys -> $test {
        my $match = TestHTML.parse( %tests{$test}<tag> );
        #diag ">>>>>>>>>>>>>>>";
        #diag $match.gist;
        #diag "---------------";
        #diag %tests{$test}<struct>.gist;
        #diag "<<<<<<<<<<<<<<<";
        is-deeply
            $match,
            %tests{$test}<struct>,
            $test;
    }
}, "Matches";

subtest {
    my $match;

    $match = TestHTML.parse("< a>");
    nok($match.defined, "space before tag name");
}, "Non-matches";

done-testing;

# vim: ft=perl6
